// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matching.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canSwipeTarget = `-- name: CanSwipeTarget :one
WITH viewer AS (
    SELECT u.id, u.gender, u.birth_date, p.location, pref.min_age, pref.max_age, pref.max_distance_km, pref.genders
    FROM users u
    JOIN profiles p ON p.user_id = u.id
    JOIN user_preferences pref ON pref.user_id = u.id
    JOIN privacy_consents consent
      ON consent.user_id = u.id
     AND consent.purpose = 'matching_gender_preferences'
     AND consent.withdrawn_at IS NULL
    WHERE u.id = $3
      AND u.status = 'active'
      AND p.onboarding_completed
      AND p.location IS NOT NULL
      AND cardinality(pref.genders) > 0
)
SELECT EXISTS (
    SELECT 1
    FROM viewer v
    JOIN users candidate ON candidate.id = $1 AND candidate.status = 'active'
    JOIN profiles candidate_profile
      ON candidate_profile.user_id = candidate.id
     AND candidate_profile.onboarding_completed
     AND candidate_profile.location IS NOT NULL
    JOIN user_preferences candidate_pref ON candidate_pref.user_id = candidate.id
    JOIN privacy_consents candidate_consent
      ON candidate_consent.user_id = candidate.id
     AND candidate_consent.purpose = 'matching_gender_preferences'
     AND candidate_consent.withdrawn_at IS NULL
    WHERE cardinality(candidate_pref.genders) > 0
      AND candidate.gender = ANY(v.genders)
      AND v.gender = ANY(candidate_pref.genders)
      AND EXTRACT(YEAR FROM age($2::timestamptz, candidate.birth_date))::integer
          BETWEEN v.min_age AND v.max_age
      AND EXTRACT(YEAR FROM age($2::timestamptz, v.birth_date))::integer
          BETWEEN candidate_pref.min_age AND candidate_pref.max_age
      AND ST_DWithin(
          v.location,
          candidate_profile.location,
          LEAST(v.max_distance_km, candidate_pref.max_distance_km)::float8 * 1000.0
      )
      AND EXISTS (
          SELECT 1 FROM photos photo
          WHERE photo.user_id = candidate.id AND photo.is_primary AND photo.deleted_at IS NULL
      )
      AND NOT EXISTS (
          SELECT 1 FROM matches match
          WHERE match.user_low_id = LEAST(v.id, candidate.id)
            AND match.user_high_id = GREATEST(v.id, candidate.id)
      )
) AS allowed
`

type CanSwipeTargetParams struct {
	TargetID pgtype.UUID        `json:"target_id"`
	AsOf     pgtype.Timestamptz `json:"as_of"`
	ActorID  pgtype.UUID        `json:"actor_id"`
}

func (q *Queries) CanSwipeTarget(ctx context.Context, arg CanSwipeTargetParams) (bool, error) {
	row := q.db.QueryRow(ctx, canSwipeTarget, arg.TargetID, arg.AsOf, arg.ActorID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const countSwipesSince = `-- name: CountSwipesSince :one
SELECT count(*) FROM swipes WHERE actor_id = $1 AND created_at >= $2
`

type CountSwipesSinceParams struct {
	ActorID   pgtype.UUID        `json:"actor_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountSwipesSince(ctx context.Context, arg CountSwipesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSwipesSince, arg.ActorID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureDiscoveryReady = `-- name: EnsureDiscoveryReady :one
SELECT EXISTS (
    SELECT 1
    FROM users u
    JOIN profiles p ON p.user_id = u.id
    JOIN user_preferences pref ON pref.user_id = u.id
    JOIN privacy_consents consent
      ON consent.user_id = u.id
     AND consent.purpose = 'matching_gender_preferences'
     AND consent.withdrawn_at IS NULL
    WHERE u.id = $1
      AND u.status = 'active'
      AND p.onboarding_completed
      AND p.location IS NOT NULL
      AND cardinality(pref.genders) > 0
      AND EXISTS (
          SELECT 1 FROM photos photo
          WHERE photo.user_id = u.id AND photo.is_primary AND photo.deleted_at IS NULL
      )
) AS ready
`

func (q *Queries) EnsureDiscoveryReady(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ensureDiscoveryReady, userID)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}

const getMatchByPair = `-- name: GetMatchByPair :one
SELECT id, user_low_id, user_high_id, matched_at, unmatched_at, unmatched_by FROM matches WHERE user_low_id = $1 AND user_high_id = $2
`

type GetMatchByPairParams struct {
	UserLowID  pgtype.UUID `json:"user_low_id"`
	UserHighID pgtype.UUID `json:"user_high_id"`
}

func (q *Queries) GetMatchByPair(ctx context.Context, arg GetMatchByPairParams) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByPair, arg.UserLowID, arg.UserHighID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.UserLowID,
		&i.UserHighID,
		&i.MatchedAt,
		&i.UnmatchedAt,
		&i.UnmatchedBy,
	)
	return i, err
}

const getSwipe = `-- name: GetSwipe :one
SELECT id, actor_id, target_id, action, created_at FROM swipes WHERE actor_id = $1 AND target_id = $2
`

type GetSwipeParams struct {
	ActorID  pgtype.UUID `json:"actor_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) GetSwipe(ctx context.Context, arg GetSwipeParams) (Swipe, error) {
	row := q.db.QueryRow(ctx, getSwipe, arg.ActorID, arg.TargetID)
	var i Swipe
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.TargetID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const getVisibleMatchingPhoto = `-- name: GetVisibleMatchingPhoto :one
SELECT photo.id, photo.user_id, photo.storage_key, photo.mime_type
FROM photos photo
WHERE photo.id = $1
  AND photo.is_primary
  AND photo.deleted_at IS NULL
  AND (
      photo.user_id = $2
      OR EXISTS (
          SELECT 1 FROM matches match
          WHERE match.user_low_id = LEAST($2::uuid, photo.user_id)
            AND match.user_high_id = GREATEST($2::uuid, photo.user_id)
            AND match.unmatched_at IS NULL
      )
      OR EXISTS (
          SELECT 1
          FROM users viewer_user
          JOIN profiles viewer_profile ON viewer_profile.user_id = viewer_user.id
          JOIN user_preferences viewer_pref ON viewer_pref.user_id = viewer_user.id
          JOIN privacy_consents viewer_consent
            ON viewer_consent.user_id = viewer_user.id
           AND viewer_consent.purpose = 'matching_gender_preferences'
           AND viewer_consent.withdrawn_at IS NULL
          JOIN users owner_user ON owner_user.id = photo.user_id AND owner_user.status = 'active'
          JOIN profiles owner_profile
            ON owner_profile.user_id = owner_user.id
           AND owner_profile.onboarding_completed
           AND owner_profile.location IS NOT NULL
          JOIN user_preferences owner_pref ON owner_pref.user_id = owner_user.id
          JOIN privacy_consents owner_consent
            ON owner_consent.user_id = owner_user.id
           AND owner_consent.purpose = 'matching_gender_preferences'
           AND owner_consent.withdrawn_at IS NULL
          WHERE viewer_user.id = $2
            AND viewer_user.status = 'active'
            AND viewer_profile.onboarding_completed
            AND viewer_profile.location IS NOT NULL
            AND cardinality(viewer_pref.genders) > 0
            AND cardinality(owner_pref.genders) > 0
            AND owner_user.gender = ANY(viewer_pref.genders)
            AND viewer_user.gender = ANY(owner_pref.genders)
            AND EXTRACT(YEAR FROM age($3::timestamptz, owner_user.birth_date))::integer
                BETWEEN viewer_pref.min_age AND viewer_pref.max_age
            AND EXTRACT(YEAR FROM age($3::timestamptz, viewer_user.birth_date))::integer
                BETWEEN owner_pref.min_age AND owner_pref.max_age
            AND ST_DWithin(
                viewer_profile.location,
                owner_profile.location,
                LEAST(viewer_pref.max_distance_km, owner_pref.max_distance_km)::float8 * 1000.0
            )
            AND NOT EXISTS (
                SELECT 1 FROM swipes swipe
                WHERE swipe.actor_id = viewer_user.id AND swipe.target_id = owner_user.id
            )
      )
  )
  AND NOT EXISTS (
      SELECT 1 FROM blocks block
      WHERE (block.blocker_id = $2 AND block.blocked_id = photo.user_id)
         OR (block.blocker_id = photo.user_id AND block.blocked_id = $2)
  )
`

type GetVisibleMatchingPhotoParams struct {
	PhotoID  pgtype.UUID        `json:"photo_id"`
	ViewerID pgtype.UUID        `json:"viewer_id"`
	AsOf     pgtype.Timestamptz `json:"as_of"`
}

type GetVisibleMatchingPhotoRow struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	StorageKey string      `json:"storage_key"`
	MimeType   string      `json:"mime_type"`
}

func (q *Queries) GetVisibleMatchingPhoto(ctx context.Context, arg GetVisibleMatchingPhotoParams) (GetVisibleMatchingPhotoRow, error) {
	row := q.db.QueryRow(ctx, getVisibleMatchingPhoto, arg.PhotoID, arg.ViewerID, arg.AsOf)
	var i GetVisibleMatchingPhotoRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StorageKey,
		&i.MimeType,
	)
	return i, err
}

const hasPositiveReverseSwipe = `-- name: HasPositiveReverseSwipe :one
SELECT EXISTS (
    SELECT 1 FROM swipes
    WHERE actor_id = $1
      AND target_id = $2
      AND action IN ('like', 'superlike')
) AS positive
`

type HasPositiveReverseSwipeParams struct {
	TargetID pgtype.UUID `json:"target_id"`
	ActorID  pgtype.UUID `json:"actor_id"`
}

func (q *Queries) HasPositiveReverseSwipe(ctx context.Context, arg HasPositiveReverseSwipeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPositiveReverseSwipe, arg.TargetID, arg.ActorID)
	var positive bool
	err := row.Scan(&positive)
	return positive, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (blocker_id, blocked_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (blocker_id, blocked_id) DO NOTHING
`

type InsertBlockParams struct {
	BlockerID pgtype.UUID        `json:"blocker_id"`
	BlockedID pgtype.UUID        `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock, arg.BlockerID, arg.BlockedID, arg.CreatedAt)
	return err
}

const insertMatch = `-- name: InsertMatch :one
INSERT INTO matches (id, user_low_id, user_high_id, matched_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_low_id, user_high_id) DO UPDATE
SET user_low_id = EXCLUDED.user_low_id
RETURNING id, user_low_id, user_high_id, matched_at, unmatched_at, unmatched_by
`

type InsertMatchParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserLowID  pgtype.UUID        `json:"user_low_id"`
	UserHighID pgtype.UUID        `json:"user_high_id"`
	MatchedAt  pgtype.Timestamptz `json:"matched_at"`
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, insertMatch,
		arg.ID,
		arg.UserLowID,
		arg.UserHighID,
		arg.MatchedAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.UserLowID,
		&i.UserHighID,
		&i.MatchedAt,
		&i.UnmatchedAt,
		&i.UnmatchedBy,
	)
	return i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (id, reporter_id, reported_id, reason, description, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, reporter_id, reported_id, reason, description, status, created_at, resolved_at
`

type InsertReportParams struct {
	ID          pgtype.UUID        `json:"id"`
	ReporterID  pgtype.UUID        `json:"reporter_id"`
	ReportedID  pgtype.UUID        `json:"reported_id"`
	Reason      string             `json:"reason"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.ID,
		arg.ReporterID,
		arg.ReportedID,
		arg.Reason,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReportedID,
		&i.Reason,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertSwipe = `-- name: InsertSwipe :one
INSERT INTO swipes (id, actor_id, target_id, action, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (actor_id, target_id) DO NOTHING
RETURNING id, actor_id, target_id, action, created_at
`

type InsertSwipeParams struct {
	ID        pgtype.UUID        `json:"id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	TargetID  pgtype.UUID        `json:"target_id"`
	Action    string             `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSwipe(ctx context.Context, arg InsertSwipeParams) (Swipe, error) {
	row := q.db.QueryRow(ctx, insertSwipe,
		arg.ID,
		arg.ActorID,
		arg.TargetID,
		arg.Action,
		arg.CreatedAt,
	)
	var i Swipe
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.TargetID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const interactionBlocked = `-- name: InteractionBlocked :one
SELECT EXISTS (
    SELECT 1 FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
       OR (blocker_id = $2 AND blocked_id = $1)
) AS blocked
`

type InteractionBlockedParams struct {
	FirstUserID  pgtype.UUID `json:"first_user_id"`
	SecondUserID pgtype.UUID `json:"second_user_id"`
}

func (q *Queries) InteractionBlocked(ctx context.Context, arg InteractionBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, interactionBlocked, arg.FirstUserID, arg.SecondUserID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listActiveMatches = `-- name: ListActiveMatches :many
SELECT
    match.id, match.user_low_id, match.user_high_id, match.matched_at, match.unmatched_at, match.unmatched_by,
    other.id AS other_user_id,
    other.display_name,
    other_profile.bio,
    other_profile.city,
    other.last_active_at AS other_last_active_at,
    photo.id AS primary_photo_id
FROM matches match
JOIN users other ON other.id = CASE
    WHEN match.user_low_id = $1 THEN match.user_high_id
    ELSE match.user_low_id
END
JOIN profiles other_profile ON other_profile.user_id = other.id
JOIN photos photo ON photo.user_id = other.id AND photo.is_primary AND photo.deleted_at IS NULL
WHERE (match.user_low_id = $1 OR match.user_high_id = $1)
  AND match.unmatched_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM blocks block
      WHERE (block.blocker_id = $1 AND block.blocked_id = other.id)
         OR (block.blocker_id = other.id AND block.blocked_id = $1)
  )
  AND (
      $2::timestamptz IS NULL
      OR match.matched_at < $2::timestamptz
      OR (
          match.matched_at = $2::timestamptz
          AND match.id < $3::uuid
      )
  )
ORDER BY match.matched_at DESC, match.id DESC
LIMIT $4
`

type ListActiveMatchesParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	CursorMatchedAt pgtype.Timestamptz `json:"cursor_matched_at"`
	CursorMatchID   pgtype.UUID        `json:"cursor_match_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListActiveMatchesRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserLowID         pgtype.UUID        `json:"user_low_id"`
	UserHighID        pgtype.UUID        `json:"user_high_id"`
	MatchedAt         pgtype.Timestamptz `json:"matched_at"`
	UnmatchedAt       pgtype.Timestamptz `json:"unmatched_at"`
	UnmatchedBy       pgtype.UUID        `json:"unmatched_by"`
	OtherUserID       pgtype.UUID        `json:"other_user_id"`
	DisplayName       pgtype.Text        `json:"display_name"`
	Bio               pgtype.Text        `json:"bio"`
	City              pgtype.Text        `json:"city"`
	OtherLastActiveAt pgtype.Timestamptz `json:"other_last_active_at"`
	PrimaryPhotoID    pgtype.UUID        `json:"primary_photo_id"`
}

func (q *Queries) ListActiveMatches(ctx context.Context, arg ListActiveMatchesParams) ([]ListActiveMatchesRow, error) {
	rows, err := q.db.Query(ctx, listActiveMatches,
		arg.UserID,
		arg.CursorMatchedAt,
		arg.CursorMatchID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMatchesRow{}
	for rows.Next() {
		var i ListActiveMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserLowID,
			&i.UserHighID,
			&i.MatchedAt,
			&i.UnmatchedAt,
			&i.UnmatchedBy,
			&i.OtherUserID,
			&i.DisplayName,
			&i.Bio,
			&i.City,
			&i.OtherLastActiveAt,
			&i.PrimaryPhotoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryCandidates = `-- name: ListDiscoveryCandidates :many
WITH viewer AS (
    SELECT
        u.id,
        u.gender,
        u.birth_date,
        p.location,
        p.interests,
        p.questionnaire,
        pref.min_age,
        pref.max_age,
        pref.max_distance_km,
        pref.genders
    FROM users u
    JOIN profiles p ON p.user_id = u.id
    JOIN user_preferences pref ON pref.user_id = u.id
    JOIN privacy_consents consent
      ON consent.user_id = u.id
     AND consent.purpose = 'matching_gender_preferences'
     AND consent.withdrawn_at IS NULL
    WHERE u.id = $4
      AND u.status = 'active'
      AND p.onboarding_completed
      AND p.location IS NOT NULL
      AND cardinality(pref.genders) > 0
),
eligible AS (
    SELECT
        candidate.id AS user_id,
        candidate.display_name,
        EXTRACT(YEAR FROM age($5::timestamptz, candidate.birth_date))::integer AS age,
        candidate.gender,
        candidate.last_active_at,
        candidate_profile.bio,
        candidate_profile.interests,
        candidate_profile.city,
        candidate_profile.questionnaire,
        photo.id AS primary_photo_id,
        ST_Distance(v.location, candidate_profile.location)::float8 / 1000.0 AS distance_km,
        LEAST(v.max_distance_km, candidate_pref.max_distance_km)::float8 AS effective_distance_km,
        v.interests AS viewer_interests,
        v.questionnaire AS viewer_questionnaire
    FROM viewer v
    JOIN users candidate ON candidate.id <> v.id AND candidate.status = 'active'
    JOIN profiles candidate_profile
      ON candidate_profile.user_id = candidate.id
     AND candidate_profile.onboarding_completed
     AND candidate_profile.location IS NOT NULL
    JOIN user_preferences candidate_pref ON candidate_pref.user_id = candidate.id
    JOIN privacy_consents candidate_consent
      ON candidate_consent.user_id = candidate.id
     AND candidate_consent.purpose = 'matching_gender_preferences'
     AND candidate_consent.withdrawn_at IS NULL
    JOIN photos photo
      ON photo.user_id = candidate.id
     AND photo.is_primary
     AND photo.deleted_at IS NULL
    WHERE cardinality(candidate_pref.genders) > 0
      AND candidate.gender = ANY(v.genders)
      AND v.gender = ANY(candidate_pref.genders)
      AND EXTRACT(YEAR FROM age($5::timestamptz, candidate.birth_date))::integer
          BETWEEN v.min_age AND v.max_age
      AND EXTRACT(YEAR FROM age($5::timestamptz, v.birth_date))::integer
          BETWEEN candidate_pref.min_age AND candidate_pref.max_age
      AND ST_DWithin(
          v.location,
          candidate_profile.location,
          LEAST(v.max_distance_km, candidate_pref.max_distance_km)::float8 * 1000.0
      )
      AND NOT EXISTS (
          SELECT 1 FROM swipes swipe
          WHERE swipe.actor_id = v.id AND swipe.target_id = candidate.id
      )
      AND NOT EXISTS (
          SELECT 1 FROM blocks block
          WHERE (block.blocker_id = v.id AND block.blocked_id = candidate.id)
             OR (block.blocker_id = candidate.id AND block.blocked_id = v.id)
      )
      AND NOT EXISTS (
          SELECT 1 FROM matches match
          WHERE match.user_low_id = LEAST(v.id, candidate.id)
            AND match.user_high_id = GREATEST(v.id, candidate.id)
      )
),
components AS (
    SELECT
        eligible.user_id, eligible.display_name, eligible.age, eligible.gender, eligible.last_active_at, eligible.bio, eligible.interests, eligible.city, eligible.questionnaire, eligible.primary_photo_id, eligible.distance_km, eligible.effective_distance_km, eligible.viewer_interests, eligible.viewer_questionnaire,
        COALESCE(
            (
                SELECT count(*)::float8
                FROM (
                    SELECT lower(trim(value)) AS item
                    FROM unnest(eligible.viewer_interests) AS value
                    WHERE trim(value) <> ''
                    INTERSECT
                    SELECT lower(trim(value)) AS item
                    FROM unnest(eligible.interests) AS value
                    WHERE trim(value) <> ''
                ) shared
            ) / NULLIF(
                (
                    SELECT count(*)::float8
                    FROM (
                        SELECT lower(trim(value)) AS item
                        FROM unnest(eligible.viewer_interests) AS value
                        WHERE trim(value) <> ''
                        UNION
                        SELECT lower(trim(value)) AS item
                        FROM unnest(eligible.interests) AS value
                        WHERE trim(value) <> ''
                    ) combined
                ),
                0
            ),
            0
        )::float8 AS interests_score,
        COALESCE(
            (
                SELECT count(*)::float8
                FROM jsonb_each(eligible.viewer_questionnaire) viewer_answer
                JOIN jsonb_each(eligible.questionnaire) candidate_answer USING (key)
                WHERE viewer_answer.value = candidate_answer.value
            ) / NULLIF(
                (
                    SELECT count(*)::float8
                    FROM (
                        SELECT jsonb_object_keys(eligible.viewer_questionnaire) AS key
                        UNION
                        SELECT jsonb_object_keys(eligible.questionnaire) AS key
                    ) questionnaire_keys
                ),
                0
            ),
            0
        )::float8 AS questionnaire_score,
        GREATEST(0, LEAST(1, 1 - eligible.distance_km / NULLIF(eligible.effective_distance_km, 0)))::float8
            AS distance_score,
        GREATEST(
            0,
            LEAST(
                1,
                1 - EXTRACT(EPOCH FROM ($5::timestamptz - eligible.last_active_at))
                    / ($6::float8 * 3600.0)
            )
        )::float8 AS activity_score
    FROM eligible
),
ranked AS (
    SELECT
        components.user_id, components.display_name, components.age, components.gender, components.last_active_at, components.bio, components.interests, components.city, components.questionnaire, components.primary_photo_id, components.distance_km, components.effective_distance_km, components.viewer_interests, components.viewer_questionnaire, components.interests_score, components.questionnaire_score, components.distance_score, components.activity_score,
        (
            components.interests_score * $7::float8
          + components.questionnaire_score * $8::float8
          + components.distance_score * $9::float8
          + components.activity_score * $10::float8
        ) / NULLIF(
            $7::float8
          + $8::float8
          + $9::float8
          + $10::float8,
            0
        ) AS total_score
    FROM components
)
SELECT
    user_id,
    display_name,
    age,
    gender,
    bio,
    interests,
    city,
    distance_km::float8 AS distance_km,
    last_active_at,
    primary_photo_id,
    interests_score,
    questionnaire_score,
    distance_score,
    activity_score,
    total_score::float8
FROM ranked
WHERE $1::float8 IS NULL
   OR total_score < $1::float8
   OR (total_score = $1::float8 AND user_id > $2::uuid)
ORDER BY total_score DESC, user_id
LIMIT $3
`

type ListDiscoveryCandidatesParams struct {
	CursorScore         pgtype.Float8      `json:"cursor_score"`
	CursorUserID        pgtype.UUID        `json:"cursor_user_id"`
	PageLimit           int32              `json:"page_limit"`
	ViewerID            pgtype.UUID        `json:"viewer_id"`
	AsOf                pgtype.Timestamptz `json:"as_of"`
	ActivityWindowHours float64            `json:"activity_window_hours"`
	InterestsWeight     float64            `json:"interests_weight"`
	QuestionnaireWeight float64            `json:"questionnaire_weight"`
	DistanceWeight      float64            `json:"distance_weight"`
	ActivityWeight      float64            `json:"activity_weight"`
}

type ListDiscoveryCandidatesRow struct {
	UserID             pgtype.UUID        `json:"user_id"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Age                int32              `json:"age"`
	Gender             pgtype.Text        `json:"gender"`
	Bio                pgtype.Text        `json:"bio"`
	Interests          []string           `json:"interests"`
	City               pgtype.Text        `json:"city"`
	DistanceKm         float64            `json:"distance_km"`
	LastActiveAt       pgtype.Timestamptz `json:"last_active_at"`
	PrimaryPhotoID     pgtype.UUID        `json:"primary_photo_id"`
	InterestsScore     float64            `json:"interests_score"`
	QuestionnaireScore float64            `json:"questionnaire_score"`
	DistanceScore      float64            `json:"distance_score"`
	ActivityScore      float64            `json:"activity_score"`
	TotalScore         float64            `json:"total_score"`
}

func (q *Queries) ListDiscoveryCandidates(ctx context.Context, arg ListDiscoveryCandidatesParams) ([]ListDiscoveryCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listDiscoveryCandidates,
		arg.CursorScore,
		arg.CursorUserID,
		arg.PageLimit,
		arg.ViewerID,
		arg.AsOf,
		arg.ActivityWindowHours,
		arg.InterestsWeight,
		arg.QuestionnaireWeight,
		arg.DistanceWeight,
		arg.ActivityWeight,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiscoveryCandidatesRow{}
	for rows.Next() {
		var i ListDiscoveryCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Age,
			&i.Gender,
			&i.Bio,
			&i.Interests,
			&i.City,
			&i.DistanceKm,
			&i.LastActiveAt,
			&i.PrimaryPhotoID,
			&i.InterestsScore,
			&i.QuestionnaireScore,
			&i.DistanceScore,
			&i.ActivityScore,
			&i.TotalScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInteractionPair = `-- name: LockInteractionPair :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        LEAST($1::uuid, $2::uuid)::text
        || ':' ||
        GREATEST($1::uuid, $2::uuid)::text,
        0
    )
)
`

type LockInteractionPairParams struct {
	FirstUserID  pgtype.UUID `json:"first_user_id"`
	SecondUserID pgtype.UUID `json:"second_user_id"`
}

func (q *Queries) LockInteractionPair(ctx context.Context, arg LockInteractionPairParams) error {
	_, err := q.db.Exec(ctx, lockInteractionPair, arg.FirstUserID, arg.SecondUserID)
	return err
}

const matchParticipantExists = `-- name: MatchParticipantExists :one
SELECT EXISTS (
    SELECT 1 FROM matches
    WHERE id = $1
      AND (user_low_id = $2 OR user_high_id = $2)
) AS exists
`

type MatchParticipantExistsParams struct {
	MatchID pgtype.UUID `json:"match_id"`
	ActorID pgtype.UUID `json:"actor_id"`
}

func (q *Queries) MatchParticipantExists(ctx context.Context, arg MatchParticipantExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, matchParticipantExists, arg.MatchID, arg.ActorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchUserActivity = `-- name: TouchUserActivity :exec
UPDATE users
SET last_active_at = $1
WHERE id = $2
  AND last_active_at < $1::timestamptz - interval '15 minutes'
`

type TouchUserActivityParams struct {
	ActiveAt pgtype.Timestamptz `json:"active_at"`
	UserID   pgtype.UUID        `json:"user_id"`
}

func (q *Queries) TouchUserActivity(ctx context.Context, arg TouchUserActivityParams) error {
	_, err := q.db.Exec(ctx, touchUserActivity, arg.ActiveAt, arg.UserID)
	return err
}

const unmatch = `-- name: Unmatch :execrows
UPDATE matches
SET unmatched_at = $1, unmatched_by = $2
WHERE id = $3
  AND (user_low_id = $2 OR user_high_id = $2)
  AND unmatched_at IS NULL
`

type UnmatchParams struct {
	UnmatchedAt pgtype.Timestamptz `json:"unmatched_at"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	MatchID     pgtype.UUID        `json:"match_id"`
}

func (q *Queries) Unmatch(ctx context.Context, arg UnmatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, unmatch, arg.UnmatchedAt, arg.ActorID, arg.MatchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unmatchPairForBlock = `-- name: UnmatchPairForBlock :exec
UPDATE matches
SET unmatched_at = $1, unmatched_by = $2
WHERE user_low_id = LEAST($2::uuid, $3::uuid)
  AND user_high_id = GREATEST($2::uuid, $3::uuid)
  AND unmatched_at IS NULL
`

type UnmatchPairForBlockParams struct {
	UnmatchedAt pgtype.Timestamptz `json:"unmatched_at"`
	BlockerID   pgtype.UUID        `json:"blocker_id"`
	BlockedID   pgtype.UUID        `json:"blocked_id"`
}

func (q *Queries) UnmatchPairForBlock(ctx context.Context, arg UnmatchPairForBlockParams) error {
	_, err := q.db.Exec(ctx, unmatchPairForBlock, arg.UnmatchedAt, arg.BlockerID, arg.BlockedID)
	return err
}
