// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveParticipants = `-- name: GetActiveParticipants :one
SELECT match.id, match.user_low_id, match.user_high_id, match.matched_at
FROM matches match
WHERE match.id = $1
  AND match.unmatched_at IS NULL
  AND (match.user_low_id = $2 OR match.user_high_id = $2)
  AND NOT EXISTS (
      SELECT 1 FROM blocks block
      WHERE (block.blocker_id = match.user_low_id AND block.blocked_id = match.user_high_id)
         OR (block.blocker_id = match.user_high_id AND block.blocked_id = match.user_low_id)
  )
`

type GetActiveParticipantsParams struct {
	MatchID  pgtype.UUID `json:"match_id"`
	ViewerID pgtype.UUID `json:"viewer_id"`
}

type GetActiveParticipantsRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserLowID  pgtype.UUID        `json:"user_low_id"`
	UserHighID pgtype.UUID        `json:"user_high_id"`
	MatchedAt  pgtype.Timestamptz `json:"matched_at"`
}

// Authorization in a single statement: the match must exist, still be active,
// include the viewer, and carry no block in either direction. Anything else
// returns no row, so the caller cannot tell the cases apart.
func (q *Queries) GetActiveParticipants(ctx context.Context, arg GetActiveParticipantsParams) (GetActiveParticipantsRow, error) {
	row := q.db.QueryRow(ctx, getActiveParticipants, arg.MatchID, arg.ViewerID)
	var i GetActiveParticipantsRow
	err := row.Scan(
		&i.ID,
		&i.UserLowID,
		&i.UserHighID,
		&i.MatchedAt,
	)
	return i, err
}

const getMessageByNonce = `-- name: GetMessageByNonce :one
SELECT id, match_id, sender_id, client_nonce, type, content, storage_key, read_at, created_at, deleted_at FROM messages WHERE sender_id = $1 AND client_nonce = $2
`

type GetMessageByNonceParams struct {
	SenderID    pgtype.UUID `json:"sender_id"`
	ClientNonce pgtype.UUID `json:"client_nonce"`
}

func (q *Queries) GetMessageByNonce(ctx context.Context, arg GetMessageByNonceParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByNonce, arg.SenderID, arg.ClientNonce)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.SenderID,
		&i.ClientNonce,
		&i.Type,
		&i.Content,
		&i.StorageKey,
		&i.ReadAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, match_id, sender_id, client_nonce, type, content, storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (sender_id, client_nonce) DO NOTHING
RETURNING id, match_id, sender_id, client_nonce, type, content, storage_key, read_at, created_at, deleted_at
`

type InsertMessageParams struct {
	ID          pgtype.UUID `json:"id"`
	MatchID     pgtype.UUID `json:"match_id"`
	SenderID    pgtype.UUID `json:"sender_id"`
	ClientNonce pgtype.UUID `json:"client_nonce"`
	Type        string      `json:"type"`
	Content     pgtype.Text `json:"content"`
	StorageKey  pgtype.Text `json:"storage_key"`
}

// ON CONFLICT DO NOTHING makes a replayed nonce a no-op instead of a
// duplicate; an empty result tells the repository to fetch the stored row.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.MatchID,
		arg.SenderID,
		arg.ClientNonce,
		arg.Type,
		arg.Content,
		arg.StorageKey,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.SenderID,
		&i.ClientNonce,
		&i.Type,
		&i.Content,
		&i.StorageKey,
		&i.ReadAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT
    match.id AS match_id,
    match.matched_at,
    other.id AS other_user_id,
    other.display_name,
    photo.id AS primary_photo_id,
    last_message.id AS last_message_id,
    last_message.sender_id AS last_message_sender_id,
    -- A match with no messages yet leaves the lateral join NULL; coalescing
    -- keeps the column non-null so it scans cleanly. last_message_id is what
    -- signals whether a last message actually exists.
    COALESCE(last_message.type, '')::text AS last_message_type,
    last_message.content AS last_message_content,
    last_message.created_at AS last_message_created_at,
    last_message.read_at AS last_message_read_at,
    COALESCE(unread.total, 0)::bigint AS unread_count
FROM matches match
JOIN users other ON other.id = CASE
    WHEN match.user_low_id = $1 THEN match.user_high_id
    ELSE match.user_low_id
END
LEFT JOIN photos photo ON photo.user_id = other.id AND photo.is_primary AND photo.deleted_at IS NULL
LEFT JOIN LATERAL (
    SELECT m.id, m.sender_id, m.type, m.content, m.created_at, m.read_at
    FROM messages m
    WHERE m.match_id = match.id AND m.deleted_at IS NULL
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 1
) last_message ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS total
    FROM messages m
    WHERE m.match_id = match.id
      AND m.sender_id <> $1
      AND m.read_at IS NULL
      AND m.deleted_at IS NULL
) unread ON true
WHERE (match.user_low_id = $1 OR match.user_high_id = $1)
  AND match.unmatched_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM blocks block
      WHERE (block.blocker_id = $1 AND block.blocked_id = other.id)
         OR (block.blocker_id = other.id AND block.blocked_id = $1)
  )
ORDER BY COALESCE(last_message.created_at, match.matched_at) DESC, match.id DESC
LIMIT $2
`

type ListConversationsParams struct {
	ViewerID  pgtype.UUID `json:"viewer_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListConversationsRow struct {
	MatchID              pgtype.UUID        `json:"match_id"`
	MatchedAt            pgtype.Timestamptz `json:"matched_at"`
	OtherUserID          pgtype.UUID        `json:"other_user_id"`
	DisplayName          pgtype.Text        `json:"display_name"`
	PrimaryPhotoID       pgtype.UUID        `json:"primary_photo_id"`
	LastMessageID        pgtype.UUID        `json:"last_message_id"`
	LastMessageSenderID  pgtype.UUID        `json:"last_message_sender_id"`
	LastMessageType      string             `json:"last_message_type"`
	LastMessageContent   pgtype.Text        `json:"last_message_content"`
	LastMessageCreatedAt pgtype.Timestamptz `json:"last_message_created_at"`
	LastMessageReadAt    pgtype.Timestamptz `json:"last_message_read_at"`
	UnreadCount          int64              `json:"unread_count"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.ViewerID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.MatchID,
			&i.MatchedAt,
			&i.OtherUserID,
			&i.DisplayName,
			&i.PrimaryPhotoID,
			&i.LastMessageID,
			&i.LastMessageSenderID,
			&i.LastMessageType,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
			&i.LastMessageReadAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, match_id, sender_id, client_nonce, type, content, storage_key, read_at, created_at, deleted_at FROM messages
WHERE match_id = $1
  AND deleted_at IS NULL
  AND (
      $2::timestamptz IS NULL
      OR created_at < $2::timestamptz
      OR (
          created_at = $2::timestamptz
          AND id < $3::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListMessagesBeforeParams struct {
	MatchID         pgtype.UUID        `json:"match_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorMessageID pgtype.UUID        `json:"cursor_message_id"`
	PageLimit       int32              `json:"page_limit"`
}

// Keyset pagination over (created_at, id) so concurrent inserts cannot create
// gaps or duplicates while the client pages backwards.
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore,
		arg.MatchID,
		arg.CursorCreatedAt,
		arg.CursorMessageID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.SenderID,
			&i.ClientNonce,
			&i.Type,
			&i.Content,
			&i.StorageKey,
			&i.ReadAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesRead = `-- name: MarkMessagesRead :execrows
UPDATE messages
SET read_at = $1
WHERE match_id = $2
  AND sender_id <> $3
  AND read_at IS NULL
  AND deleted_at IS NULL
  AND created_at <= $1
`

type MarkMessagesReadParams struct {
	ReadAt   pgtype.Timestamptz `json:"read_at"`
	MatchID  pgtype.UUID        `json:"match_id"`
	ViewerID pgtype.UUID        `json:"viewer_id"`
}

// Only messages the viewer received are flagged, so a read receipt can never
// be forged for one's own messages.
func (q *Queries) MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMessagesRead, arg.ReadAt, arg.MatchID, arg.ViewerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
