// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockerID pgtype.UUID        `json:"blocker_id"`
	BlockedID pgtype.UUID        `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID          pgtype.UUID        `json:"id"`
	UserLowID   pgtype.UUID        `json:"user_low_id"`
	UserHighID  pgtype.UUID        `json:"user_high_id"`
	MatchedAt   pgtype.Timestamptz `json:"matched_at"`
	UnmatchedAt pgtype.Timestamptz `json:"unmatched_at"`
	UnmatchedBy pgtype.UUID        `json:"unmatched_by"`
}

type Photo struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	StorageKey string             `json:"storage_key"`
	MimeType   string             `json:"mime_type"`
	ByteSize   int64              `json:"byte_size"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	Position   int16              `json:"position"`
	IsPrimary  bool               `json:"is_primary"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type PrivacyConsent struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Purpose       string             `json:"purpose"`
	PolicyVersion string             `json:"policy_version"`
	GrantedAt     pgtype.Timestamptz `json:"granted_at"`
	WithdrawnAt   pgtype.Timestamptz `json:"withdrawn_at"`
	Source        string             `json:"source"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	UserID              pgtype.UUID        `json:"user_id"`
	Bio                 pgtype.Text        `json:"bio"`
	Interests           []string           `json:"interests"`
	City                pgtype.Text        `json:"city"`
	Location            interface{}        `json:"location"`
	Questionnaire       []byte             `json:"questionnaire"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	FamilyID     pgtype.UUID        `json:"family_id"`
	TokenHash    []byte             `json:"token_hash"`
	ReplacedBy   pgtype.UUID        `json:"replaced_by"`
	DeviceLabel  pgtype.Text        `json:"device_label"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	Ip           *netip.Addr        `json:"ip"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason pgtype.Text        `json:"revoke_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID          pgtype.UUID        `json:"id"`
	ReporterID  pgtype.UUID        `json:"reporter_id"`
	ReportedID  pgtype.UUID        `json:"reported_id"`
	Reason      string             `json:"reason"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
}

type Swipe struct {
	ID        pgtype.UUID        `json:"id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	TargetID  pgtype.UUID        `json:"target_id"`
	Action    string             `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	DisplayName       pgtype.Text        `json:"display_name"`
	BirthDate         pgtype.Date        `json:"birth_date"`
	Gender            pgtype.Text        `json:"gender"`
	Status            string             `json:"status"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	LastActiveAt      pgtype.Timestamptz `json:"last_active_at"`
}

type UserPreference struct {
	UserID        pgtype.UUID        `json:"user_id"`
	MinAge        int16              `json:"min_age"`
	MaxAge        int16              `json:"max_age"`
	MaxDistanceKm int16              `json:"max_distance_km"`
	Genders       []string           `json:"genders"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
