// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveConsent = `-- name: FindActiveConsent :one
SELECT id, user_id, purpose, policy_version, granted_at, withdrawn_at, source, created_at FROM privacy_consents WHERE user_id = $1 AND purpose = $2 AND withdrawn_at IS NULL
`

type FindActiveConsentParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Purpose string      `json:"purpose"`
}

func (q *Queries) FindActiveConsent(ctx context.Context, arg FindActiveConsentParams) (PrivacyConsent, error) {
	row := q.db.QueryRow(ctx, findActiveConsent, arg.UserID, arg.Purpose)
	var i PrivacyConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.PolicyVersion,
		&i.GrantedAt,
		&i.WithdrawnAt,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const grantConsent = `-- name: GrantConsent :one
INSERT INTO privacy_consents (user_id, purpose, policy_version, source)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, purpose, policy_version, granted_at, withdrawn_at, source, created_at
`

type GrantConsentParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Purpose       string      `json:"purpose"`
	PolicyVersion string      `json:"policy_version"`
	Source        string      `json:"source"`
}

func (q *Queries) GrantConsent(ctx context.Context, arg GrantConsentParams) (PrivacyConsent, error) {
	row := q.db.QueryRow(ctx, grantConsent,
		arg.UserID,
		arg.Purpose,
		arg.PolicyVersion,
		arg.Source,
	)
	var i PrivacyConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.PolicyVersion,
		&i.GrantedAt,
		&i.WithdrawnAt,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const withdrawActiveConsent = `-- name: WithdrawActiveConsent :exec
UPDATE privacy_consents SET withdrawn_at = $3 WHERE user_id = $1 AND purpose = $2 AND withdrawn_at IS NULL
`

type WithdrawActiveConsentParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Purpose     string             `json:"purpose"`
	WithdrawnAt pgtype.Timestamptz `json:"withdrawn_at"`
}

func (q *Queries) WithdrawActiveConsent(ctx context.Context, arg WithdrawActiveConsentParams) error {
	_, err := q.db.Exec(ctx, withdrawActiveConsent, arg.UserID, arg.Purpose, arg.WithdrawnAt)
	return err
}
