// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearGenders = `-- name: ClearGenders :exec
UPDATE user_preferences SET genders = '{}', updated_at = now() WHERE user_id = $1
`

func (q *Queries) ClearGenders(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearGenders, userID)
	return err
}

const clearPrimaryPhoto = `-- name: ClearPrimaryPhoto :exec
UPDATE photos SET is_primary = false WHERE user_id = $1 AND is_primary AND deleted_at IS NULL
`

func (q *Queries) ClearPrimaryPhoto(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryPhoto, userID)
	return err
}

const countActivePhotos = `-- name: CountActivePhotos :one
SELECT count(*) FROM photos WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountActivePhotos(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePhotos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (id, user_id, storage_key, mime_type, byte_size, width, height, position, is_primary)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, storage_key, mime_type, byte_size, width, height, position, is_primary, created_at, deleted_at
`

type CreatePhotoParams struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	StorageKey string      `json:"storage_key"`
	MimeType   string      `json:"mime_type"`
	ByteSize   int64       `json:"byte_size"`
	Width      int32       `json:"width"`
	Height     int32       `json:"height"`
	Position   int16       `json:"position"`
	IsPrimary  bool        `json:"is_primary"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.ID,
		arg.UserID,
		arg.StorageKey,
		arg.MimeType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.Position,
		arg.IsPrimary,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StorageKey,
		&i.MimeType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, user_id, storage_key, mime_type, byte_size, width, height, position, is_primary, created_at, deleted_at FROM photos WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPhoto(ctx context.Context, id pgtype.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StorageKey,
		&i.MimeType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPreferences = `-- name: GetPreferences :one
SELECT user_id, min_age, max_age, max_distance_km, genders, created_at, updated_at FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetPreferences(ctx context.Context, userID pgtype.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.MinAge,
		&i.MaxAge,
		&i.MaxDistanceKm,
		&i.Genders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT
    user_id, bio, interests, city, questionnaire, onboarding_completed, created_at, updated_at,
    (location IS NOT NULL) AS has_location
FROM profiles
WHERE user_id = $1
`

type GetProfileRow struct {
	UserID              pgtype.UUID        `json:"user_id"`
	Bio                 pgtype.Text        `json:"bio"`
	Interests           []string           `json:"interests"`
	City                pgtype.Text        `json:"city"`
	Questionnaire       []byte             `json:"questionnaire"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	HasLocation         interface{}        `json:"has_location"`
}

func (q *Queries) GetProfile(ctx context.Context, userID pgtype.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Bio,
		&i.Interests,
		&i.City,
		&i.Questionnaire,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasLocation,
	)
	return i, err
}

const listPhotos = `-- name: ListPhotos :many
SELECT id, user_id, storage_key, mime_type, byte_size, width, height, position, is_primary, created_at, deleted_at FROM photos WHERE user_id = $1 AND deleted_at IS NULL ORDER BY position
`

func (q *Queries) ListPhotos(ctx context.Context, userID pgtype.UUID) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StorageKey,
			&i.MimeType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
			&i.Position,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhotoPosition = `-- name: SetPhotoPosition :exec
UPDATE photos SET position = $3 WHERE id = $1 AND user_id = $2
`

type SetPhotoPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Position int16       `json:"position"`
}

func (q *Queries) SetPhotoPosition(ctx context.Context, arg SetPhotoPositionParams) error {
	_, err := q.db.Exec(ctx, setPhotoPosition, arg.ID, arg.UserID, arg.Position)
	return err
}

const setPrimaryPhoto = `-- name: SetPrimaryPhoto :exec
UPDATE photos SET is_primary = true WHERE id = $1 AND user_id = $2
`

type SetPrimaryPhotoParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetPrimaryPhoto(ctx context.Context, arg SetPrimaryPhotoParams) error {
	_, err := q.db.Exec(ctx, setPrimaryPhoto, arg.ID, arg.UserID)
	return err
}

const softDeletePhoto = `-- name: SoftDeletePhoto :exec
UPDATE photos SET deleted_at = $2 WHERE id = $1
`

type SoftDeletePhotoParams struct {
	ID        pgtype.UUID        `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) SoftDeletePhoto(ctx context.Context, arg SoftDeletePhotoParams) error {
	_, err := q.db.Exec(ctx, softDeletePhoto, arg.ID, arg.DeletedAt)
	return err
}

const updateGenders = `-- name: UpdateGenders :exec
UPDATE user_preferences SET genders = $2, updated_at = now() WHERE user_id = $1
`

type UpdateGendersParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Genders []string    `json:"genders"`
}

func (q *Queries) UpdateGenders(ctx context.Context, arg UpdateGendersParams) error {
	_, err := q.db.Exec(ctx, updateGenders, arg.UserID, arg.Genders)
	return err
}

const upsertPreferences = `-- name: UpsertPreferences :exec
INSERT INTO user_preferences (user_id, min_age, max_age, max_distance_km)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    min_age = EXCLUDED.min_age,
    max_age = EXCLUDED.max_age,
    max_distance_km = EXCLUDED.max_distance_km,
    updated_at = now()
`

type UpsertPreferencesParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	MinAge        int16       `json:"min_age"`
	MaxAge        int16       `json:"max_age"`
	MaxDistanceKm int16       `json:"max_distance_km"`
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertPreferences,
		arg.UserID,
		arg.MinAge,
		arg.MaxAge,
		arg.MaxDistanceKm,
	)
	return err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (user_id, bio, interests, city, location, questionnaire, onboarding_completed)
VALUES (
    $1, $2, $3, $4,
    CASE
        WHEN $5::float8 IS NULL OR $6::float8 IS NULL THEN NULL
        ELSE ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326)::geography
    END,
    $7, $8
)
ON CONFLICT (user_id) DO UPDATE SET
    bio = EXCLUDED.bio,
    interests = EXCLUDED.interests,
    city = EXCLUDED.city,
    -- An update that carries no coordinates must preserve the stored ones;
    -- only an explicit clear_location drops them.
    location = CASE
        WHEN $9::boolean THEN NULL
        WHEN EXCLUDED.location IS NULL THEN profiles.location
        ELSE EXCLUDED.location
    END,
    questionnaire = EXCLUDED.questionnaire,
    onboarding_completed = EXCLUDED.onboarding_completed,
    updated_at = now()
`

type UpsertProfileParams struct {
	UserID              pgtype.UUID   `json:"user_id"`
	Bio                 pgtype.Text   `json:"bio"`
	Interests           []string      `json:"interests"`
	City                pgtype.Text   `json:"city"`
	Longitude           pgtype.Float8 `json:"longitude"`
	Latitude            pgtype.Float8 `json:"latitude"`
	Questionnaire       []byte        `json:"questionnaire"`
	OnboardingCompleted bool          `json:"onboarding_completed"`
	ClearLocation       bool          `json:"clear_location"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Bio,
		arg.Interests,
		arg.City,
		arg.Longitude,
		arg.Latitude,
		arg.Questionnaire,
		arg.OnboardingCompleted,
		arg.ClearLocation,
	)
	return err
}
