// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, family_id, token_hash, device_label, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateRefreshTokenParams struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	FamilyID    pgtype.UUID        `json:"family_id"`
	TokenHash   []byte             `json:"token_hash"`
	DeviceLabel pgtype.Text        `json:"device_label"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	Ip          *netip.Addr        `json:"ip"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.DeviceLabel,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, family_id, token_hash, replaced_by, device_label, user_agent, ip, expires_at, last_used_at, revoked_at, revoke_reason, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ReplacedBy,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, user_id, family_id, token_hash, replaced_by, device_label, user_agent, ip, expires_at, last_used_at, revoked_at, revoke_reason, created_at FROM refresh_tokens WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ReplacedBy,
		&i.DeviceLabel,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const replaceRefreshToken = `-- name: ReplaceRefreshToken :exec
UPDATE refresh_tokens
SET replaced_by = $2, revoked_at = $3, revoke_reason = $4, last_used_at = $3
WHERE id = $1
`

type ReplaceRefreshTokenParams struct {
	ID           pgtype.UUID        `json:"id"`
	ReplacedBy   pgtype.UUID        `json:"replaced_by"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason pgtype.Text        `json:"revoke_reason"`
}

func (q *Queries) ReplaceRefreshToken(ctx context.Context, arg ReplaceRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, replaceRefreshToken,
		arg.ID,
		arg.ReplacedBy,
		arg.RevokedAt,
		arg.RevokeReason,
	)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = $2, revoke_reason = $3
WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeAllRefreshTokensForUserParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason pgtype.Text        `json:"revoke_reason"`
}

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, arg RevokeAllRefreshTokensForUserParams) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, arg.UserID, arg.RevokedAt, arg.RevokeReason)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = $2, revoke_reason = $3
WHERE family_id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	FamilyID     pgtype.UUID        `json:"family_id"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason pgtype.Text        `json:"revoke_reason"`
}

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.FamilyID, arg.RevokedAt, arg.RevokeReason)
	return err
}
